### ISSUE TITLE
Up and down orientations not working for observers?

### ISSUE THREAD

**Issue by emilydolson** [real-itu/Evocraft-py#2]
Love this environment!

This is a super minor problem, but I was messing around with building a rocket ship by hand (to make sure I understand the interface), and it looks like `OBSERVER` blocks do not respect the `UP` and `DOWN` orientations. When I try to make one facing in either of those directions (e.g. with `client.spawnBlocks(Blocks(blocks=[Block(position=Point(x=8, y=6, z=1), type=OBSERVER, orientation=UP),]))`, I just get a north-facing observer. `NORTH`, `EAST`, `WEST`, and `SOUTH` all work fine. `UP` and `DOWN` worked fine when I tried them with `STICKY_PISTON` blocks, so this seems to just be a problem for observers. Any idea why it's happening?

**Comment by djole** [comment]
Hi Emily!
Thanks for finding out the bug. I'll check out why is it happening and get back to you.

**Comment by djole** [comment]
This is an error within the Sponge framework. Hopefully it gets fixed when the new API version comes out. I reported the issue.
